name: Check

on:
  push:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  
    - name: build
      run: cd lab5 && make 
    - name: clean
      run: cd lab5 && make clean
